import pickle

amiggerquotes=[
    "amigger and his family :joy::joy::joy:",
    "amigger and his family :joy::joy::grinning:",
    "family and his amigger :hedgehog::evergreen_tree::frog:",
    "amigger and his bushes",
    "amigger and his :bat::bat::bat::bat:",
    "amigger ate a lot of people :rolling_eyes:",
    "amigger is melting tigger5002's niggtop with 150ns pnig",
    "amigger and his son is my password :sob::key:",
    "amigger and his son was supposed be a woman :female_sign:",
    "amigger and his wife are my favorite songs about this one :clock130::heart_eyes::heart::grin::smile::smiley_cat:",
    "amigger and I will probably leave my office today :grin:",
    "amigger and his family and I can do the earthquake :shaking_face::cold_face::shaking_face::shaking_face:",
    "amigger and I can get rid the body :eye::tongue::eye:",
    "amigger and his daughter :laughing:",
    "amigger and his compression :compression:",
    "amigger and his amigger :baby_chick:",
    "amigger and flowmigger eating and drinking water :sweat_drops::joy::blush::wink::grin::slight_smile:",
    "amigger and his children :pie:",
    "amigger and the void :space_invader:",
    "amigger and his cell machine :microbe:",
    "amigger and he killed himself :joy::joy:",
    "amigger is a good :blush::relieved:",
    "amigger and his cell machine\nthe game is controller by ammeter and not you",
    "does amigger having a family",
    "hey amigger add a few minutes ago to your house :house_with_garden::wave::house:",
    "hey amigger and then I got the super intense for a few weeks and the :evergreen_tree::hedgehog::evergreen_tree::hedgehog:",
    "amigger is invading minkos and the kids :rofl::joy::sweat_smile::joy:",
    "icosamigger and the :evergreen_tree::frog:",
    "icosamigger with the floor is my password :rage:",
    "icosamigger and his mouth :stuck_out_tongue_winking_eye:",
    "icosamigger and then immediately and then immediately after that we are a bushes :grinning:",
    "icosamigger ate a lot of :cloud_rain: lol :laughing:",
    "icosamigger ate my lunch :yum:",
    "icosamigger has a personal gas station :station::fuelpump:",
    "amigger and his team :trophy: are doing well :grinning::slight_smile:",
    "amigger and i think with portals :open_file_folder::page_facing_up::stuck_out_tongue:",
    "amigger and more :heavy_plus_sign: than a week :date: or two :clock230::blush:",
    "amigger is a wuggy games :video_game::sob::wink::blush::slight_smile::joy:",
    "amigger is not a greatest cow :cow2:",
    "amigger and the email :envelope::blush:",
    "amigger and then I can get a girl pregnant :exploding_head:",
    "amigger and his work is a wuggy games :dart:",
    "amigger ate my cat :cat2::anguished:",
    "amigger is melting face :melting_face::smiling_imp:",
    "amigger is the best :shaking_face::blush:",
    "amigger and the greatest :sunglasses: cow :pig2::blush:",
    "amigger and his animals :dog2: are treated :syringe: with pie :pie::dog:",
    "amiggeration is the best crew and his team mates :trophy: who are doing well :grinning::thumbsup:"
]

pickle.dump(amiggerquotes, open("amiggerquotes.dat", "wb"))
